
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/parts/Navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "JBECP-PARSERS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className='w-screen h-screen items-center justify-center' 
            style={{
              background: "black",
              backgroundImage: `
                radial-gradient(circle at top right, rgba(255, 0, 0, 0.5), transparent 45%)
              `,
              backgroundSize: 'cover',
              backgroundPosition: 'center',
            }}>
            <Navigation />
            {children}
            <p className="text-sm font-bold text-white text-center mt-32">All Rights Reserved. 2024</p>
        </div>
      </body>
    </html>
  );
}
